### ISSUE TITLE
Button click throws TypeError

### ISSUE THREAD

**Issue by soerface** [covid-lens/covid-lens.github.io#1]
When clicking on „List Nearby Devices“, the following exception is thrown in the dev console:

```
(index):54 Uncaught TypeError: Cannot read property 'requestDevice' of undefined
    at HTMLButtonElement.onclick ((index):54)
onclick @ (index):54
(index):54 Uncaught TypeError: Cannot read property 'requestDevice' of undefined
    at HTMLButtonElement.onclick ((index):54)
onclick @ (index):54
```

Tested with Chromium Version 83.0.4103.97 (Official Build) snap (64-bit)
and Chrome Version 83.0.4103.97 (Official Build) (64-bit)
on Ubuntu 20.04.

My browser did not ask me to allow for access to bluetooth. Bluetooth is enabled in the OS and currently no device connected.

**Comment by m33x** [comment]
Hi Sören,

this is sadly normal behavior. Web Bluetooth is not widely supported yet and even within Chrome the support differs by OS. If you find a way how to get up and running on Ubuntu please let me know.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API (expand Chrome to see different OSs)

Best,
Max

**Comment by covid-lens** [comment]
Hi Sören,

I improved the error handling. Instead of testing user agents, I now check for the the presence of the navigator.bluetooth object. Moreover, I added a table of supported platforms to the FAQ.

By the way; I figured out how to get it up and running on Ubuntu Linux:
https://twitter.com/m33x/status/1274618626356785152

I will close this for now :)

Thanks for bringing this up!

**Comment by soerface** [comment]
Thanks for the heads up about the experimental flag! Might be useful to check for user agent to hint about the flag / explain it directly instead of needing to scroll down, find the link, go to twitter and then to github and then searching for `chrome://flags/#enable-experimental-web-platform-features`.

You could still improve the error handling of the button. I've enabled the flag, the button is there, but it is still nothing happening when clicking. Just some visual feedback so the user won't wait and gets unpatient. In my case, the error is now:

Uncaught (in promise) DOMException: Bluetooth adapter not available.

Guess you can't do much about it, and it's an experimental feature anyway.

**Comment by m33x** [comment]
Just restart the bluetooth service and restart Chrome then it should work 😀

**Comment by soerface** [comment]
No, it does not. I even tried restarting the whole OS, just to be sure.

Any system logs I can provide you?

EDIT: okay, CHROME works, CHROMIUM not, despite being the same version. Well… :man_shrugging: Maybe snap is messing with the browser.
